[package]
name = "curve1024"
version = "0.1.0"
edition = "2024"

[dependencies]
subtle = "2.6.1"
sha2 = "0.10"
rand = "0.9"
clap = { version = "4", features = ["derive"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "curve1024-sig"
path = "src/bin/curve1024_sig.rs"

[build-dependencies]
toml = "0.8"
serde = { version = "1", features = ["derive"] }
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "signature_bench"
harness = false
